### ISSUE TITLE
Latest release download location

### ISSUE THREAD

**Issue by reznet** [notahat/midi_patchbay#10]
Hi, I have been happily using Midi Patchbay in Mojave (thanks for making it available!) and am looking to upgrade to Catalina, but the upgrader said Midi Patchbay would not be compatible.  From the [homepage](http://notahat.com/midi_patchbay/) I found this GitHub project and noticed in the readme there are two more recent releases, 1.0.4 and 1.1.0, but I cannot find where they are published.  Would you mind updating the readme with a link to where to download 1.1.0, or perhaps publish it to the Releases page?

**Comment by XENONChromatic** [comment]
Hey @reznet 

@danomatika 's builds are here: http://docs.danomatika.com/releases/midipatchbay/ 

I've been running first test 1 and then test 2 without issues on Catalina. That being said, @notahat is working on updates as there were a few changes that needed to be ironed out relating to Catalina. Once those are sorted I'm sure he'll have an official release and update the readme.

**Comment by reznet** [comment]
@carbon43 thanks for the quick reply!  I'm running test2 in Catalina now and it's good enough for my needs.  I did find a small UI issue that I'll open a separate issue for.

**Comment by danomatika** [comment]
@reznet My builds are unofficial and simply called version "1.0.4." I took the existing PRs, integrated some deprecation changes, and threw in some UI update ideas. I would suggest building and testing @notahat's current work before opening any new issues.

EDIT: I updated the text on the release link to reflect that the 1.0.4 test builds are unofficial.
