### ISSUE TITLE
Where can we download Version 1.1.0

### ISSUE THREAD

**Issue by mlostekk** [notahat/midi_patchbay#13]
I cant find it in the releases section

**Comment by liamlacey** [comment]
I would also like to know this.

Or do we just need to build the project ourselves?

**Comment by ffont** [comment]
I built the project myself, it compiles easily, but it would be nice to add 1.1.0 on a release, even if it is marked as pre-release.

**Comment by liamlacey** [comment]
Yes I too very easily just built the project myself in the end, but I agree that it would be nice.

**Comment by mlostekk** [comment]
Sure, compiling yourself is possible, but imagine how many people are out there that never heard of xcode

**Comment by mmontag** [comment]
How about setting up Github actions to build releases? Anybody have experience with this?
https://rhonabwy.com/2020/05/09/continuous-integration-with-github-actions-for-macos-and-ios-projects/

**Comment by XENONChromatic** [comment]
One other possible option would be reaching out to @notahat on Twitter. I did that a while back and he did respond. I'm running what I guess would be considered RC2 (at least, thats what I was calling it) that @danomatika had compiled, but it would be nice to have an official compiled version on here.

**Comment by danomatika** [comment]
As a follow up, I recently picked up a new MBP 13 with the M1 cpu, so I plan to make a universal2 (intel+arm64) build as well.

**Comment by lokkiikkol** [comment]
definitely needs a compiled version! can somebody share one?

**Comment by danomatika** [comment]
I put a link in PR https://github.com/notahat/midi_patchbay/issues/7#issuecomment-758072512

**Comment by julientaq** [comment]
Folks, did you see that?

http://docs.danomatika.com/releases/midipatchbay/

**Comment by yaros-eu** [comment]
Feel free to check out my modernized and simplified version of this app!

https://github.com/drummer-codes/midi_router

![image](https://github.com/notahat/midi_patchbay/assets/69213136/c5359505-01fc-4ffc-8d76-60e8346ee017)
